{
 "title": "Artifactory",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dockerhub Cache Hit Ratio",
   "type": "gauge",
   "description": "Shows the ratio of Dockerhub cache hits versus downloads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1-(sum(increase(jfrog_rt_access{repo_path=~\".*list\\\\.manifest.*\",repo_path=~\".*-cache.*\", action_response=\"ACCEPTED DEPLOY\"}[1m]))/sum(increase(jfrog_rt_access{repo_path=~\".*list\\\\.manifest.*\", action_response=\"ACCEPTED DOWNLOAD\"}[1m])))",
     "legendFormat": "cache hit ratio"
    }
   ]
  },
  {
   "title": "Dockerhub Pull Requests Rolling 1H Average",
   "type": "graph",
   "description": "Shows Dockerhub pull requests over rolling 1H average.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(jfrog_rt_service_message{message=~\".*downloading.*\",message=~\".*manifests.*\",message=~\".*docker\\\\.io.*\"}[1h]))"
    }
   ]
  },
  {
   "title": "Dockerhub Cache Hits and Downloads",
   "type": "graph",
   "description": "Shows Dockerhub cache hits and downloads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jfrog_rt_access{repo_path=~\".*list\\\\.manifest.*\",repo_path=~\".*-cache.*\", action_response=\"ACCEPTED DEPLOY\"}[1m]))",
     "legendFormat": "cache hit"
    },
    {
     "expr": "sum(increase(jfrog_rt_access{repo_path=~\".*list\\\\.manifest.*\", action_response=\"ACCEPTED DOWNLOAD\"}[1m]))",
     "legendFormat": "download"
    }
   ]
  },
  {
   "title": "Dockerhub Pull Requests",
   "type": "graph",
   "description": "Shows Dockerhub pull requests over the time period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jfrog_rt_service_message{message=~\".*downloading.*\",message=~\".*manifests.*\",message=~\".*docker\\\\.io.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Top 10 Users Performing Docker Pull Requests",
   "type": "bargauge",
   "description": "Shows the top users making docker pull requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (increase(jfrog_rt_access{repo_path=~\".*list\\\\.manifest.*\", action_response=\"ACCEPTED DEPLOY\"}[$__range]) > 0 ) ) ",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  {
   "title": "Top 10 IPs Performing Docker Pull Requests",
   "type": "bargauge",
   "description": "Shows the top users making docker pull requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (ip) (increase(jfrog_rt_access{repo_path=~\".*list\\\\.manifest.*\", action_response=\"ACCEPTED DEPLOY\"}[$__range]) > 0 ) ) ",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Accessed Images",
   "type": "bargauge",
   "description": "Shows the top images that have been requested.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk( 10, sum by (dockerImage) (increase(jfrog_rt_req_by_docker_image{dockerImage!=\"\",return_status=\"200\"}[$__range]) > 0))",
     "legendFormat": "{{dockerImage}}"
    }
   ]
  },
  {
   "title": "Accessed Docker Repos",
   "type": "bargauge",
   "description": "Shows the top docker repos that have been requested.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk( 10, sum by (dockerRepo) (increase(jfrog_rt_req_by_docker_repo{dockerRepo!=\"\",return_status=\"200\"}[$__range]) > 0))",
     "legendFormat": "{{dockerRepo}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HTTP 500 Errors",
   "type": "graph",
   "description": "Shows HTTP 5XX errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jfrog_rt_req{return_status=~\"5.*\"}[$__range])"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "description": "Shows HTTP response codes over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (return_status) (increase(jfrog_rt_req[$__range]))",
     "legendFormat": "{{return_status}}"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "graph",
   "description": "Shows Artifactory log errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jfrog_rt_log_level{log_level=\"ERROR\"}[$__range])"
    }
   ]
  },
  {
   "title": "Download Data Transfers",
   "type": "graph",
   "description": "Shows the download data transfers from this Artifactory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jfrog_rt_data_download[1m]))"
    }
   ]
  },
  {
   "title": "Upload Data Transfers",
   "type": "graph",
   "description": "Shows the upload data transfers from this Artifactory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jfrog_rt_data_upload[1m]))"
    }
   ]
  },
  {
   "title": "Accessed Repos",
   "type": "bargauge",
   "description": "Shows the top repositories by requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk( 10, sum by (repo) (increase(jfrog_rt_req_by_repo{repo!=\"\",return_status=\"200\"}[$__range]) > 0))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Accessed Artifacts",
   "type": "bargauge",
   "description": "Shows the top artifacts that have been requested.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk( 10, sum by (artifact) (increase(jfrog_rt_req_by_artifact{artifact!=\"\",return_status=\"200\"}[$__range]) > 0))",
     "legendFormat": "{{artifact}}"
    }
   ]
  },
  {
   "title": "Data Transfers Uploads by Repo",
   "type": "bargauge",
   "description": "Top active repositories by data transfers uploads.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (repo) (increase(jfrog_rt_data_upload_by_repo{repo!=\"\"}[$__range])) > 0)",
     "legendFormat": "{{repo}}"
    },
    {
     "expr": "topk(10, sum by (dockerRepo) (increase(jfrog_rt_data_upload_by_docker_repo{dockerRepo!=\"\"}[$__range])) > 0)",
     "legendFormat": "{{dockerRepo}}"
    }
   ]
  },
  {
   "title": "Data Transfers Downloads by Repo",
   "type": "bargauge",
   "description": "Top active repositories by data transfers downloads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (repo) (increase(jfrog_rt_data_download_repo{repo!=\"\"}[$__range])) > 0)",
     "legendFormat": "{{repo}}"
    },
    {
     "expr": "topk(10, sum by (dockerRepo) (increase(jfrog_rt_data_download_docker_repo{dockerRepo!=\"\"}[$__range])) > 0)",
     "legendFormat": "{{dockerRepo}}"
    }
   ]
  },
  {
   "title": "Top IPs by Uploads",
   "type": "bargauge",
   "description": "Shows the top uploading IPs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_address) (increase(jfrog_rt_data_upload_by_remote_address[$__range])) > 0)",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "Top IPs by Downloads",
   "type": "bargauge",
   "description": "Shows the top downloading remote IPs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_address) (increase(jfrog_rt_data_download_by_remote_address[$__range])) > 0)",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Audit Actions by Users",
   "type": "bargauge",
   "description": "Shows the top users by actions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (user) (increase(jfrog_rt_access_audit{user!=\"UNKNOWN\", user!=\"_system_\",user!=\"\"}[$__range])) )",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Accepted Deploys by User",
   "type": "bargauge",
   "description": "Shows accepted deploys by user.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (user) (increase(jfrog_rt_access{user!=\"UNKNOWN\", user!=\"_system_\", action_response=\"ACCEPTED DEPLOY\"}[$__range]) > 0 ) ) ",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Denied Login by IP",
   "type": "bargauge",
   "description": "Shows the denied login attempts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (ip) (increase(jfrog_rt_access{user!=\"UNKNOWN\", user!=\"_system_\", action_response=\"DENIED LOGIN\"}[$__range]) > 0 ) ) ",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Denied Actions by User",
   "type": "bargauge",
   "description": "Shows denied actions by user.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (user) (increase(jfrog_rt_access{user!=\"UNKNOWN\", user!=\"_system_\", action_response=\"DENIED\"}[$__range]) > 0 ) ) ",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Denied Login by User and IP",
   "type": "bargauge",
   "description": "Shows the denied login attempts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (user,ip) (increase(jfrog_rt_access{user!=\"UNKNOWN\", user!=\"_system_\", action_response=\"DENIED LOGIN\"}[$__range]) > 0 ) ) ",
     "legendFormat": "{{user}}-{{ip}}"
    }
   ]
  },
  {
   "title": "Denied Actions by IP",
   "type": "bargauge",
   "description": "Shows denied actions by IP address.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (ip) (increase(jfrog_rt_access{action_response=\"DENIED\"}[$__range]) > 0 ) ) ",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}