{
 "title": "Artifactory Metrics",
 "tags": [
  "jfrog",
  "artifactory"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_step", "label": "Granularity", "query": "1m,5m,10m,15m,20m,30m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "tomcat_app",
    "query": {
     "query": "label_values(tomcat_threads_busy_threads{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Artifactory Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1,label_replace(kube_pod_container_info{namespace=\"$namespace\",container=\"artifactory\"}, \"version\", \"$1\", \"image\", \".+:(.+)\"))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Artifacts Count",
   "type": "stat",
   "description": "Shows the total number of artifacts stored in all repositories.",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jfrt_stg_summary_files_total{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Artifacts Size",
   "type": "stat",
   "description": "Shows the total size of all artifacts stored in Artifactory.\n\nNote: The information about storage is updated infrequently (once in 6 hours), so the number that you see here is just an approximation.",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jfrt_stg_summary_size_bytes{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files in Trash",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jfrt_stg_summary_repo_files_total{namespace=\"$namespace\", pod=~\"$pod\", type=\"NA\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Binaries",
   "type": "stat",
   "description": "Shows the total number of binaries stored in Artifactory (data from the last checkpoint).",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jfrt_stg_summary_checkpoint_binaries_total{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Used Storage",
   "type": "stat",
   "description": "Shows the total number of bytes used by Artifactory storage (information is from the last checkpoint)",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jfrt_stg_summary_checkpoint_binaries_size_bytes{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Trash Size",
   "type": "stat",
   "description": "Shows the total size of all artifacts in the trash",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jfrt_stg_summary_repo_size_bytes{namespace=\"$namespace\", pod=~\"$pod\", type=\"NA\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime - $pod",
   "type": "stat",
   "description": "The uptime of the JVM - pod $pod",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "description": "Shows the total number of repositories in Artifactory",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jfrt_repo_by_type_total{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Package Types",
   "type": "stat",
   "description": "Shows the total number of package types that are used in repositories of all customers",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(jfrt_repo_by_type_total{namespace=\"$namespace\", pod=~\"$pod\"}) by (package))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Federated Repositories",
   "type": "stat",
   "description": "Shows the total number of federated repositories in the selected JPD",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jfrt_repo_by_type_total{namespace=\"$namespace\", pod=~\"$pod\", type=\"Federated\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and JVM Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Artifactory CPU Usage",
     "type": "timeseries",
     "description": "Artifactory container CPU usage",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(system_cpu_usage{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod) + sum(process_cpu_usage{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod)",
       "legendFormat": "{{pod}} - artifactory"
      }
     ]
    },
    {
     "title": "JVM Memory Usage (% of Max Memory)",
     "type": "timeseries",
     "description": "The memory utilization ratio: Displays the ratio of used /committed JVM memory to the maximum available JVM memory",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod)\n/\nsum(jvm_memory_max_bytes{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod)",
       "legendFormat": "Used Memory - {{pod}}"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod)\n/\nsum(jvm_memory_max_bytes{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod)",
       "legendFormat": "Committed Memory - {{pod}}"
      }
     ]
    },
    {
     "title": "JVM - Threads By State",
     "type": "timeseries",
     "description": "The number of threads in various states within the JVM.\n\nThread States:\n\n- **RUNNABLE**: Threads that are actively executing Java code.\n- **BLOCKED**: Threads that are waiting to acquire a monitor lock to enter a synchronized block or method.\n- **WAITING**: Threads that are waiting indefinitely for another thread to notify or interrupt them.\n- **TIMED_WAITING**: Threads that are waiting for a specific period, such as through a Thread.sleep() or similar operation.\n- **TERMINATED**: Threads that have completed their execution and terminated.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(jvm_threads_states_threads{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod, state) > 0",
       "legendFormat": "threads-{{state}} - {{pod}}"
      }
     ]
    },
    {
     "title": "JVM Memory Usage (Bytes)",
     "type": "timeseries",
     "description": "The amount of memory that JVM uses:\n\n- **Committed Memory** is the amount of memory that JVM allocated from the operating system\n- **Used Memory** is the amount of memory that JVM actually uses\n- **Max Memory** is the maximal amount of memory available to JVM\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod)",
       "legendFormat": "Used Memory - {{pod}}"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod)",
       "legendFormat": "Committed Memory - {{pod}}"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}) by (pod)",
       "legendFormat": "Max Memory - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat - Threads ($tomcat_app)",
     "type": "timeseries",
     "description": "- **Busy Threads** -  The current number of threads in Tomcat's thread pool that are actively processing requests.\n- **Idle Threads** - The current number of threads in Tomcat's thread pool that are waiting for incoming requests.\n- **Max Threads** - The maximum number of threads configured for Tomcat's thread pool.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "repeat": "tomcat_app",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(tomcat_threads_busy_threads{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", name=~\"$tomcat_app\"}) by (name, pod)",
       "legendFormat": "Busy Threads {{name}} / {{pod}}"
      },
      {
       "expr": "max(tomcat_threads_current_threads{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", name=~\"$tomcat_app\"} \n    -\ntomcat_threads_busy_threads{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", name=~\"$tomcat_app\"}\n) by (name, pod)",
       "legendFormat": "Idle Threads {{name}} / {{pod}}"
      },
      {
       "expr": "max(tomcat_threads_config_max_threads{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", name=~\"$tomcat_app\"}) by (name, pod)",
       "legendFormat": "Max Threads {{name}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Tomcat - Connections ($tomcat_app)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "repeat": "tomcat_app",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(tomcat_connections_current_connections{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", name=~\"$tomcat_app\"}) by (pod)",
       "legendFormat": "Active Connections - {{pod}}"
      },
      {
       "expr": "max(tomcat_connections_config_max_connections{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", name=~\"$tomcat_app\"}) by (pod)",
       "legendFormat": "Max Connections - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(jfrt_db_connections_active_total{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "Active Connections - {{pod}}"
      },
      {
       "expr": "max(jfrt_db_connections_idle_total{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "idle Connections - {{pod}}"
      },
      {
       "expr": "max(jfrt_db_connections_active_total{namespace=\"$namespace\", pod=~\"$pod\"} + jfrt_db_connections_idle_total{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "Total Connections - {{pod}}"
      }
     ]
    },
    {
     "title": "DB Queries Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(db_query_duration_seconds_count{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}[$__rate_interval]))",
       "legendFormat": "Total queries"
      },
      {
       "expr": "sum(increase(db_query_duration_seconds_count{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", slow=\"y\"}[$__rate_interval]))",
       "legendFormat": "Slow queries"
      }
     ]
    },
    {
     "title": "DB Queries Rate (queries / minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(db_query_duration_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}[$__rate_interval])) * 60",
       "legendFormat": "DB queries per minute"
      }
     ]
    },
    {
     "title": "DB Queries Count - Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(db_query_duration_seconds_count{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Total queries - {{pod}}"
      },
      {
       "expr": "sum(increase(db_query_duration_seconds_count{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", slow=\"y\"}[$__rate_interval])) by (pod) > 0",
       "legendFormat": "Slow queries - {{pod}}"
      }
     ]
    },
    {
     "title": "DB Queries Rate (queries / minute) - Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(db_query_duration_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}[$__rate_interval])) by (pod) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Intensive DB Queries - Wait Time / second",
     "type": "timeseries",
     "description": "This graph lists queries that we suspect to be a source of a significant load on DB.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10,\n    sum(\n        rate(db_query_duration_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}[$__rate_interval])\n    ) by (type,tables) >= 0.5\n)",
       "legendFormat": "{{type}} {{tables}}"
      }
     ]
    },
    {
     "title": "Slow Queries - Max Duration (sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max_over_time(db_query_duration_seconds_max{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\", slow=\"y\"}[ $__rate_interval]) > 0",
       "legendFormat": "{{type}} {{tables}}"
      }
     ]
    },
    {
     "title": "DB-Intensive Artifactory Activities",
     "type": "timeseries",
     "description": "This graph lists Artifactory activities that spend \"too much\" time, waiting for DB queries.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    rate(db_query_by_trigger_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}[$__rate_interval])\n) by (trigger, pkg) >= 0.5",
       "legendFormat": "{{pkg}} - {{trigger}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heavy Background Activities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduled Jobs with High Work Time (> 10% of thread time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 434 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(jobs_exec_seconds_sum{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}[$__rate_interval])) by (name) > 0.1",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Work Queues with High Work Time (> 10% of thread time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 434 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_execution_duration_seconds_sum{application=\"Artifactory\", namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"}[$__rate_interval])) by (name) > 0.1",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Activity - Uploads / Downloads / Redirects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Binary Downloads - Per Storage Provider",
     "type": "timeseries",
     "description": "The total number of binary downloads - per provider",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(jfsh_binaries_download_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Binary Uploads - Per Storage Provider",
     "type": "timeseries",
     "description": "The total number of binary uploads - per storage provider",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(jfsh_binaries_upload_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signed URL Redirects - Per Storage Provider",
     "type": "timeseries",
     "description": "The total number of signed URL redirects per storage provider",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(jfsh_signed_url_redirect_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (source)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Download Speed",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "avg(jfsh_binaries_download_speed{quantile=~\"0\\\\.01|0\\\\.5|0\\\\.99\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, quantile)",
       "legendFormat": "{{quantile}} "
      }
     ]
    },
    {
     "title": "Upload/Download Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(increase(jfsh_binaries_upload_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (id)",
       "legendFormat": "Upload [ {{id}} ]"
      },
      {
       "expr": "sum(increase(jfsh_binaries_download_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (id)",
       "legendFormat": "Download [ {{id}} ]"
      }
     ]
    },
    {
     "title": "Average Upload Speed",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "avg(jfsh_binaries_upload_speed{quantile=~\"0\\\\.01|0\\\\.5|0\\\\.99\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, quantile)",
       "legendFormat": "{{quantile}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "min(app_disk_free_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"})",
       "legendFormat": "Free Disk Space (min)"
      },
      {
       "expr": "max(app_disk_used_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=\"artifactory\"})",
       "legendFormat": "Used Disk Space (max)"
      }
     ]
    }
   ]
  }
 ]
}