{
 "title": "Artifactory & Xray Drill Downs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rt_return_status",
    "label": "Artifactory Response Code",
    "query": "label_values(jfrog_rt_req, return_status)"
   },
   {
    "name": "repo",
    "label": "Repository",
    "query": "label_values(jfrog_rt_req, repo)"
   },
   {
    "name": "artifact",
    "label": "Artifact",
    "query": "label_values(jfrog_rt_req, artifact)"
   },
   {
    "name": "dockerRepo",
    "label": "Docker Repo",
    "query": "label_values(jfrog_rt_req,dockerRepo)"
   },
   {
    "name": "dockerImage",
    "label": "Docker Image",
    "query": "label_values(jfrog_rt_req,dockerImage)"
   },
   {
    "name": "xray_return_status",
    "label": "Xray Response Code",
    "query": "label_values(jfrog_xray_req,return_status)"
   }
  ]
 },
 "panels": [
  { "title": "Artifactory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accessed Images",
   "type": "graph",
   "description": "Shows the top images that have been requested.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk( 10, sum by (dockerImage) (increase(jfrog_rt_req_by_docker_image{dockerImage=\"$dockerImage\",return_status=\"200\"}[$__range]) > 0))",
     "legendFormat": "{{dockerImage}}"
    }
   ]
  },
  {
   "title": "Accessed Docker Repos",
   "type": "graph",
   "description": "Shows the top docker repos that have been requested.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk( 10, sum by (dockerRepo) (increase(jfrog_rt_req_by_docker_repo{dockerRepo=\"$dockerRepo\",return_status=\"200\"}[$__range]) > 0))",
     "legendFormat": "{{dockerRepo}}"
    }
   ]
  },
  {
   "title": "Accessed Artifacts",
   "type": "graph",
   "description": "Shows the top artifacts that have been requested.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (artifact) (increase(jfrog_rt_req_by_artifact{artifact=\"$artifact\",return_status=\"200\"}[$__range]))",
     "legendFormat": "{{artifact}}"
    }
   ]
  },
  {
   "title": "Accessed Repos",
   "type": "graph",
   "description": "Shows the top repositories by requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk( 10, sum by (repo) (increase(jfrog_rt_req_by_repo{repo=\"$repo\",return_status=\"200\"}[$__range]) > 0))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "description": "Shows HTTP response codes over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (return_status) (increase(jfrog_rt_req{return_status=\"$rt_return_status\"}[$__range]))",
     "legendFormat": "{{return_status}}"
    }
   ]
  },
  { "title": "Xray", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "description": "Shows HTTP response codes over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (return_status) (increase(jfrog_xray_req{return_status=\"$xray_return_status\"}[$__range]))",
     "legendFormat": "{{return_status}}"
    }
   ]
  }
 ]
}