{
 "title": "Xray Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Xray Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1,label_replace(kube_pod_container_info{namespace=\"$namespace\",container=\"xray-server\"}, \"version\", \"$1\", \"image\", \".+:(.+)\"))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "CPU and Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", pod=~\".*xray.*\", container!=\"\", container!=\"POD\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\", pod=~\".*xray.*\", container!=\"\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(server_go_memstats_heap_objects_total{service=\"xray-auth-metrics\"})",
     "legendFormat": "Total Heap Objects"
    }
   ]
  },
  {
   "title": "Heap Usage MBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg(server_go_memstats_heap_in_use_bytes{service=\"xray-auth-metrics\"}) / (1024 * 1024)",
     "legendFormat": "Heap Used MBytes"
    },
    {
     "expr": "avg(server_go_memstats_heap_reserved_bytes{service=\"xray-auth-metrics\"}) / (1024 * 1024)",
     "legendFormat": "Heap Reserved MBytes"
    },
    {
     "expr": "avg(server_go_memstats_heap_allocated_bytes{service=\"xray-auth-metrics\"}) / (1024 * 1024)",
     "legendFormat": "Heap Allocated MBytes"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Connections Usage",
     "type": "timeseries",
     "description": "% of Xray DB connection used",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "avg(db_connection_pool_in_use_total{service=\"xray-auth-metrics\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "avg(db_connection_pool_idle_total{service=\"xray-auth-metrics\"})",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Database Connections Usage %",
     "type": "timeseries",
     "description": "% of Xray DB connection used",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(db_connection_pool_in_use_total{service=\"xray-auth-metrics\"} / db_connection_pool_max_open_total{service=\"xray-auth-metrics\"}*100)",
       "legendFormat": "Percent"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Xray Services Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(server_app_disk_free_bytes{service=\"xray-auth-metrics\"})",
       "legendFormat": "Free Disk Space"
      },
      {
       "expr": "avg(server_app_disk_used_bytes{service=\"xray-auth-metrics\"})",
       "legendFormat": "Used Disk Space"
      }
     ]
    }
   ]
  }
 ]
}