{
 "title": "Xray Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(server_sys_cpu_ratio{service=\"xray-auth-metrics\"}) * 100",
     "legendFormat": "System CPU Usage (Avg)"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(server_sys_memory_used_bytes{service=\"xray-auth-metrics\"})",
     "legendFormat": "System Memory Used (Avg)"
    },
    {
     "expr": "avg(server_sys_memory_free_bytes{service=\"xray-auth-metrics\"})",
     "legendFormat": "System Memory Free (Avg)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(server_app_disk_free_bytes{service=\"xray-auth-metrics\"})",
     "legendFormat": "Storage Free Bytes (Avg)"
    },
    {
     "expr": "avg(server_app_disk_used_bytes{service=\"xray-auth-metrics\"})",
     "legendFormat": "Storage Used Bytes (Avg)"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(server_go_memstats_heap_objects_total{service=\"xray-auth-metrics\"})",
     "legendFormat": "Total Heap Objects (Avg)"
    },
    {
     "expr": "avg(server_go_memstats_heap_in_use_bytes{service=\"xray-auth-metrics\"})",
     "legendFormat": "Heap Used Bytes (Avg)"
    },
    {
     "expr": "avg(server_go_memstats_heap_reserved_bytes{service=\"xray-auth-metrics\"})",
     "legendFormat": "Heap Reserved Bytes (Avg)"
    },
    {
     "expr": "avg(server_go_memstats_heap_allocated_bytes{service=\"xray-auth-metrics\"})",
     "legendFormat": "Heap Allotted Bytes (Avg)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "description": "Shows HTTP response codes over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (DownstreamStatus) (count_over_time({agent=\"fluentd\",service=\"xray\"} | json | (log_source=~\"jfrog.xray.*.request\", DownstreamStatus > 0) [$__interval]))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "description": "Shows Artifactory log errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({agent=\"fluentd\",service=\"xray\"} | json | (log_source=~\"jfrog.xray.*.service\") [$__range]))"
    }
   ]
  },
  {
   "title": "HTTP 500 Errors",
   "type": "timeseries",
   "description": "Shows HTTP 5XX errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({agent=\"fluentd\",service=\"xray\"} | json | (log_source=~\"jfrog.xray.*.request\", DownstreamStatus=~\"5.*\") [$__range]))"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "timeseries",
   "description": "Shows Artifactory log errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({agent=\"fluentd\",service=\"xray\"} | json | (log_source=~\"jfrog.xray.*\", log_level=\"ERROR\") [$__range]))"
    }
   ]
  }
 ]
}