{
 "title": "Xray",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "description": "Shows HTTP response codes over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (return_status) (increase(jfrog_xray_req[1m]))",
     "legendFormat": "{{return_status}}"
    }
   ]
  },
  {
   "title": "Xray Errors",
   "type": "graph",
   "description": "Shows Xray errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jfrog_xray_log_level{log_level=\"ERROR\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP 5XX Errors",
   "type": "graph",
   "description": "Shows Xray HTTP 5XX errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jfrog_xray_req{return_status=~\"5.*\"}[1m]))"
    }
   ]
  }
 ]
}