{
 "title": "Artifactory (New)",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "avg(sys_cpu_ratio{}) * 100", "legendFormat": "System CPU Usage (Avg)" }
     ]
    },
    {
     "title": "System Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "avg(sys_memory_used_bytes)", "legendFormat": "System Memory Used (Avg)" },
      { "expr": "avg(sys_memory_free_bytes)", "legendFormat": "System Memory Free (Avg)" }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "avg(app_disk_free_bytes)", "legendFormat": "Storage Free Bytes (Avg)" },
      { "expr": "avg(app_disk_used_bytes)", "legendFormat": "Storage Used Bytes (Avg)" },
      {
       "expr": "avg(jfrt_storage_current_total_size_bytes)",
       "legendFormat": "Storage Total Bytes (Avg)"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "avg(jfrt_runtime_heap_processors_total)",
       "legendFormat": "Total Heap Processors (Avg)"
      },
      {
       "expr": "avg(jfrt_runtime_heap_freememory_bytes)",
       "legendFormat": "Heap Free Bytes (Avg)"
      },
      {
       "expr": "avg(jfrt_runtime_heap_maxmemory_bytes)",
       "legendFormat": "Heap Max Bytes (Avg)"
      },
      {
       "expr": "avg(jfrt_runtime_heap_totalmemory_bytes)",
       "legendFormat": "Heap Total Bytes (Avg)"
      }
     ]
    },
    {
     "title": "Garbage Collection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg(jfrt_artifacts_gc_duration_seconds)"
      },
      {
       "expr": "avg(jfrt_artifacts_gc_binaries_total)"
      },
      {
       "expr": "avg(jfrt_artifacts_gc_size_cleaned_bytes)"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dockerhub Pull Requests Rolling 1H Average",
     "type": "graph",
     "description": "Shows Dockerhub pull requests over rolling 1H average.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\".*/api/docker/.*/blobs/.*\", repo!=\"\", artifact!=\"\", (request_method=\"HEAD\" or request_method=\"GET\"))[1h]))"
      }
     ]
    },
    {
     "title": "Dockerhub Pull Requests",
     "type": "timeseries",
     "description": "Shows Dockerhub pull requests over the time period.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\".*/api/docker/.*/blobs/.*\", repo!=\"\", artifact!=\"\", (request_method=\"HEAD\" or request_method=\"GET\"))[1h]))"
      }
     ]
    },
    {
     "title": "Top 10 Users Performing Docker Pull Requests",
     "type": "bargauge",
     "description": "Shows the top users making docker pull requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by (username) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.access\", action_response = \"ACCEPTED DEPLOY\", repo_path=~\".*_uploads.*\") [1h])))",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Top 10 IPs Performing Docker Pull Requests",
     "type": "bargauge",
     "description": "Shows the top users making docker pull requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by (ip) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.access\", action_response = \"ACCEPTED DEPLOY\", repo_path=~\".*_uploads.*\") [1h])))",
       "legendFormat": "{{ip}}"
      }
     ]
    },
    {
     "title": "Accessed Images",
     "type": "bargauge",
     "description": "Shows the top images that have been requested.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by (artifact) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\"/api/docker/.*\", repo!=\"\", repo!=\"NULL\", repo!=\"latest\", artifact!=\"\", artifact!=\"NULL\", artifact!=\"latest\") [$__range])))",
       "legendFormat": "{{artifact}}"
      }
     ]
    },
    {
     "title": "Accessed Docker Repos",
     "type": "bargauge",
     "description": "Shows the top docker repos that have been requested.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by (repo) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\"/api/docker/.*\", repo!=\"\", repo!=\"NULL\", repo!=\"latest\", artifact!=\"\", artifact!=\"NULL\", artifact!=\"latest\") [$__range])))",
       "legendFormat": "{{repo}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP 500 Errors",
   "type": "graph",
   "description": "Shows HTTP 5XX errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\",return_status=~\"5.*\") [$__range]))"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "graph",
   "description": "Shows Artifactory log errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.service\", log_level=\"ERROR\") [$__range]))"
    }
   ]
  },
  {
   "title": "Upload Data Transfers",
   "type": "graph",
   "description": "Shows the upload data transfers from this Artifactory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum((sum_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", response_content_length>0) | unwrap response_content_length [1h])))"
    }
   ]
  },
  {
   "title": "Download Data Transfers",
   "type": "graph",
   "description": "Shows the download data transfers from this Artifactory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum((sum_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_content_length>0) | unwrap request_content_length [1h])))"
    }
   ]
  },
  {
   "title": "Accessed Artifacts",
   "type": "bargauge",
   "description": "Shows the top artifacts that have been requested.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (artifact) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\"/api/docker/.*\", repo!=\"\", repo!=\"NULL\", repo!=\"latest\", artifact!=\"\", artifact!=\"NULL\", artifact!=\"latest\") [$__range]))",
     "legendFormat": "{{artifact}}"
    }
   ]
  },
  {
   "title": "Accessed Repos",
   "type": "bargauge",
   "description": "Shows the top repositories by requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (repo) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\"/api/docker/.*\", repo!=\"\", repo!=\"NULL\", repo!=\"latest\", artifact!=\"\", artifact!=\"NULL\", artifact!=\"latest\") [$__range]))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Data Transfers Uploads by Repo",
   "type": "bargauge",
   "description": "Top active repositories by data transfers uploads.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (repo) (sum_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\"/api/docker/.*\", repo!=\"\", repo!=\"NULL\", repo!=\"latest\", artifact!=\"\", artifact!=\"NULL\", artifact!=\"latest\", request_content_length > 0) | unwrap request_content_length [1h])))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Data Transfers Downloads by Repo",
   "type": "bargauge",
   "description": "Top active repositories by data transfers downloads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (repo) (sum_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\"/api/docker/.*\", repo!=\"\", repo!=\"NULL\", repo!=\"latest\", artifact!=\"\", artifact!=\"NULL\", artifact!=\"latest\", response_content_length > 0) | unwrap response_content_length [1h])))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Top IPs by Downloads",
   "type": "bargauge",
   "description": "Shows the top downloading remote IPs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_address) (sum_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\"/api/docker/.*\", repo!=\"\", repo!=\"NULL\", repo!=\"latest\", artifact!=\"\", artifact!=\"NULL\", artifact!=\"latest\", response_content_length > 0) | unwrap response_content_length [1h])))",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "Top IPs by Uploads",
   "type": "bargauge",
   "description": "Shows the top uploading IPs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_address) (sum_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\", request_url=~\"/api/docker/.*\", repo!=\"\", repo!=\"NULL\", repo!=\"latest\", artifact!=\"\", artifact!=\"NULL\", artifact!=\"latest\", request_content_length > 0) | unwrap request_content_length [1h])))",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "description": "Shows HTTP response codes over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (return_status) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | (log_source=\"jfrog.rt.artifactory.request\") [$__interval]))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Audit Actions by Users",
   "type": "bargauge",
   "description": "Shows the top users by actions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | log_source = \"jfrog.rt.artifactory.access\", username != \"NA \", username !~ \"token.*\", username != \"_system_ \" [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Accepted Deploys by User",
   "type": "bargauge",
   "description": "Shows accepted deploys by user.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | log_source = \"jfrog.rt.artifactory.access\", action_response=\"ACCEPTED DEPLOY\", username != \"NA \" [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Denied Login by IP",
   "type": "bargauge",
   "description": "Shows the denied login attempts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (ip) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | log_source = \"jfrog.rt.artifactory.access\", action_response=\"DENIED LOGIN\", username != \"NA \" [$__range])))",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Denied Actions by User",
   "type": "bargauge",
   "description": "Shows denied actions by user.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | log_source = \"jfrog.rt.artifactory.access\", action_response=~\"DENIED.*\", username != \"NA \" [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Denied Login by User and IP",
   "type": "bargauge",
   "description": "Shows the denied login attempts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (ip, username) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | log_source = \"jfrog.rt.artifactory.access\", action_response=\"DENIED LOGIN\", username != \"NA \" [$__range])))",
     "legendFormat": "{{ip}} / {{username}}"
    }
   ]
  },
  {
   "title": "Denied Actions by IP",
   "type": "bargauge",
   "description": "Shows denied actions by IP address.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (ip) (count_over_time({agent=\"fluentd\",service=\"artifactory\"} | json | log_source = \"jfrog.rt.artifactory.access\", action_response=~\"DENIED.*\", username != \"NA \" [$__range])))",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}